export type Role = 'owner' | 'admin' | 'moderator' | 'member';
export type RolePermission = 'edit_space' | 'invite_members' | 'remove_members' | 'manage_messages' | 'pin_messages' | 'publish_channel' | 'send_announcement' | 'manage_invites' | 'manage_roles';
export type CustomRole = { id: string; name: string; color: string; priority: number; permissions: Partial<Record<RolePermission, boolean>> };
export type PollOption = { id: string; text: string };
export type ThemeName = 'day' | 'evening' | 'night';
export type ChatKind = 'dm' | 'group' | 'channel';
export type MediaKind = 'image' | 'video' | 'audio' | 'file';
export type Profile = {
  uid: string;
  username: string;
  displayName: string;
  bio?: string;
  avatar?: string;
  cover?: string;
  mood?: string;
  roar?: string;
  roarUntil?: number;
  createdAt: number;
};
export type Chat = {
  id: string;
  kind: ChatKind;
  title: string;
  description?: string;
  avatar?: string;
  creatorId: string;
  public?: boolean;
  createdAt: number;
  updatedAt: number;
  lastText?: string;
  lastSenderId?: string;
  inviteCode?: string;
  pinnedMessageId?: string;
};
export type Media = { kind: MediaKind; name: string; url: string; size: number; mime: string };
export type Message = {
  id: string;
  chatId: string;
  senderId: string;
  text: string;
  media?: Media;
  replyTo?: string;
  forwardedFrom?: string;
  type?: 'normal' | 'poll' | 'announcement';
  poll?: { question: string; options: PollOption[]; allowChange?: boolean };
  createdAt: number;
  editedAt?: number;
  deleted?: boolean;
  status?: 'sending' | 'sent' | 'error';
};
export type Notice = { id: string; type: string; title: string; body: string; chatId?: string; createdAt: number; read?: boolean };
